// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqGM1Urlqdm4Uc8Pd5gBuzfZ7oicCSCBE',
    appId: '1:353337839676:web:b5d576465e4b55f75ab339',
    messagingSenderId: '353337839676',
    projectId: 'sportsiiitd',
    authDomain: 'sportsiiitd.firebaseapp.com',
    storageBucket: 'sportsiiitd.appspot.com',
    measurementId: 'G-D0XXJBJ1NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvvecfCZDh-XxFsQPF53voGXY0oXEYeaI',
    appId: '1:353337839676:android:6e8a0034e294a8ea5ab339',
    messagingSenderId: '353337839676',
    projectId: 'sportsiiitd',
    storageBucket: 'sportsiiitd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnctUAO8R3gSt5-L4yx-t_ONpsOEODjO8',
    appId: '1:353337839676:ios:9f39ae5ddd2fddc75ab339',
    messagingSenderId: '353337839676',
    projectId: 'sportsiiitd',
    storageBucket: 'sportsiiitd.appspot.com',
    iosBundleId: 'com.example.sportsIiitd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnctUAO8R3gSt5-L4yx-t_ONpsOEODjO8',
    appId: '1:353337839676:ios:8a94725eac4c44305ab339',
    messagingSenderId: '353337839676',
    projectId: 'sportsiiitd',
    storageBucket: 'sportsiiitd.appspot.com',
    iosBundleId: 'com.example.sportsIiitd.RunnerTests',
  );
}
